name: deployment_dev

on:
  push:
    branches:
      - develop
      - add_dev_cicd

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run poetry image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.8

    - name: add test repository
      run: poetry config repositories.test https://test.pypi.org/legacy/

    - name: upload lib
      run: poetry build && poetry publish -r test
