name: Upload Python Dev Package

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: develop

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run poetry image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.8

    - name: upload lib
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PIP_TOKEN }}
      run: poetry config repositories.test https://test.pypi.org/legacy/ && poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI && poetry build && poetry publish -r test
