name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Bootstrap poetry
      shell: bash
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

    - name: Update PATH
      shell: bash
      run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest --cov=pyverless --cov-fail-under=80 --cov-report xml
